### ISSUE TITLE
Missing "\begin{document}"

### ISSUE THREAD

**Issue by sssalkr** [andybarry/beamer-commands#1]
Hey Andrew, 
followed your suggestions here: https://abarry.org/the-new-complete-guide-to-embedded-videos-in-beamer-under-linux/ but get the "missing \begin{document}" error when compiling the tex file with \usepackge{extrabeamercmds} in the preamble. Commenting this package resolves the error. Ever came across that problem? Would be so cool to use pdfpresenterconsole with a video...

**Comment by andybarry** [comment]
Does the pdfpc example with movies work for you?

https://github.com/pdfpc/pdfpc/releases/download/v4.3.0/pdfpc-video-example.zip

**Comment by sssalkr** [comment]
Yes, it does. And using \usepackage{multimedia} with \movie{} gives a perfect result. Life can be simple. Still, somethings wrong with the instructions on the website : ) Thank you for the quick response

**Comment by andybarry** [comment]
Can you send me the .tex file you are using?  The extrabeamercmds should work and if it's broken I do want to fix the instructions.  Are you doing the ```\usepackage``` before your ```\begin{document}```?

**Comment by sssalkr** [comment]
Even this here results in endless compiling...
```
\documentclass{beamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{microtype}
\usepackage{lmodern}

\usepackage{extrabeamercmds}

\begin{document}
\begin{frame}
Test
\end{frame}

\end{document}
```

**Comment by andybarry** [comment]
Weird, that works fine for me on a fresh checkout of this repo.  Are you using ```pdflatex test.tex``` or some other command to compile it?

**Comment by sssalkr** [comment]
pdflatex via texmaker

Used the filelink on the website for the extrabeamercmds.sty.file

**Comment by andybarry** [comment]
What version of pdflatex is it?  I'm using:

```
$ pdflatex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
**
```

**Comment by sssalkr** [comment]
```
LOG FILE :
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex 2018.10.21) 24 NOV 2019 19:31
entering extended mode
restricted \write18 enabled.
%&-line parsing enabled.
```

**Comment by sssalkr** [comment]
Surprisingly, I had the \begin{document} error only in the original tex-file. This WME is compiled until I kill the process manually

**Comment by andybarry** [comment]
Ok, I'm stumped.  If it's working well enough for you to use pdfpc, I guess we can close the issue.

You could also try pasting in the contents of extrabeamercmds.sty into your .tex file and/or start deleting stuff in that file until it works.  I'm certainly curious.

**Comment by sssalkr** [comment]
You mean including the code in the preamble and compiling bits of it by commenting?

**Comment by andybarry** [comment]
Yes, exactly

**Comment by sssalkr** [comment]
If you meant that:
Compiling only with the first line: »Missing \begin{document}«. Compiling with the whole code: Endless compiling. : )

By the way: It’s definitely possible that I’m making a serious silly make somewhere here

**Comment by andybarry** [comment]
Just putting ```\newcommand{\A}{\mathcal{A}}``` in your document preamble makes it fail?

**Comment by sssalkr** [comment]
No, that works

**Comment by sssalkr** [comment]
Oh god. Problem solved. Wrong »file« : )

**Comment by sssalkr** [comment]
Began thinking, wenn I read the first line »!DOCTYPE html«. Please don’t ask. Sorry for wasting your time. Now I have this MWE and »environment textblock undefined«
```
\documentclass{beamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{microtype}
\usepackage{lmodern}
\usepackage{extrabeamercmds}
\begin{document}
\begin{frame}
Test
\end{frame}
\fullFrameMovie{x.mp4}{x.jpg}
\end{document}
```

**Comment by andybarry** [comment]
Haha, all good, happens to all of us.  Is it working now or do you have a different error?  Can you compile the example in the repo?

**Comment by sssalkr** [comment]
Full disclosure: I did a »save as...« with the link in the instructions which resulted in a file with a proper name : (

Everything is fine now. It’s the textpos-package that was missing

**Comment by andybarry** [comment]
Cool, glad you got it sorted!
